# Essentials
brew "stow"
brew "mise"

# CLI Tools
brew "neovim"
brew "zsh"
brew "tree"
brew "zoxide"
brew "fzf"
brew "coreutils"
brew "delta"
brew "ripgrep"
brew "posting"

# Dev Tools
cask "docker"
cask "visual-studio-code"
cask "android-studio"
cask "pgadmin4"
cask "lm-studio"
brew "postgresql"
brew "mongodb-community"

# Communication
cask "slack"
cask "zoom"

# Browsers
cask "google-chrome"
cask "brave-browser"
cask "firefox"
cask "google-chrome@canary"

# Utilities
cask "google-drive"
cask "karabiner-elements"
cask "the-unarchiver"
cask "simplenote"
cask "obs"

# Media & Graphics
cask "gimp"
cask "inkscape"
cask "vlc"
cask "qcad"

# Fonts
cask "font-jetbrains-mono-nerd-font"
