# # Base16 Solarized Light - kitty color config
# # Scheme by Ethan Schoonover (modified by aramisgithub)
#
# # macos_titlebar_color #eee8d5
# # cursor #586e75
# cursor #d33682
# cursor_text_color #fdf6e3
# background #fdf6e3
# foreground #586e75
# selection_background #586e75
# selection_foreground #fdf6e3
# url_color #657b83
# active_border_color #d9cca1
# inactive_border_color #eee8d5
# active_tab_background #586e75
# active_tab_foreground #fdf6e3
# inactive_tab_background #93a1a1
# inactive_tab_foreground #657b83
#
# # normal
# color0 #fdf6e3
# color1 #dc322f
# color2 #859900
# color3 #b58900
# color4 #268bd2
# color5 #6c71c4
# color6 #2aa198
# color7 #586e75
#
# # bright
# color8 #839496
# color9 #cb4b16
# color10 #eee8d5
# color11 #93a1a1
# color12 #657b83
# color13 #073642
# color14 #d33682
# color15 #586e75
#
# # The basic 16 colors
# # black
# color0 #073642
# color8 #93a1a1
#
# # red
# color1 #dc322f
# color9 #cb4b16
#
# # green
# color2  #859900
# color10 #586e75
#
# # yellow
# color3  #b58900
# color11 #657b83
#
# # blue
# color4  #268bd2
# color12 #839496
#
# # magenta
# color5  #d33682
# color13 #6c71c4
#
# # cyan
# color6  #2aa198
# color14 #93a1a1
#
# # white
# color7  #eee8d5
# color15 #fdf6e3



cursor #f879ea
cursor_text_color #000000
background #fdf6e3
foreground #44555b
selection_background #eee8d5   
selection_foreground #44555b
url_color #2570aa  
active_border_color #000000  
inactive_border_color #839496   
active_tab_background #000000
active_tab_foreground #d3cebd
inactive_tab_background #839496   
inactive_tab_foreground #d3cebd  

color0  #000000
color1  #ae2927
color2  #6c7d07
color3  #8b6b0c
color4  #2570aa
color5  #963785
color6  #22746e
color7  #d3cebd
               
color8  #839496
color9  #f6aeab
color10 #eaf0cb
color11 #f8ebb2
color12 #cbe1f4
color13 #eeb8e4
color14 #b2e8e3
color15 #eee8d5

# cursor      #f879ea
# background  #fdf6e3
# text        #44555b
# bold text   #44565b

